{% set python_min = '3.10' %}
{% set name = "pymt_dbseabed" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d0f6fae6c423c2b2a59d6c390042fc7e238888a4e305b1d7f2ebfa262c2b352b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bmi_dbseabed

test:
  requires:
    - bmi-tester
    - python {{ python_min }}
  imports:
    - pymt_dbseabed
  source_files:
    - notebooks/config_file.yaml
  commands:
    - cd notebooks  # [unix]
    - bmi-test pymt_dbseabed.bmi:DbSeabedData --config-file=config_file.yaml --root-dir=. -vvv  # [unix]

about:
  home: https://github.com/gantian127/pymt_dbseabed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyMT plugin for dbSEABED dataset.
  description: |
    pymt_dbseabed is a package that converts bmi_dbseabed package into a reusable, 
    plug-and-play data component for PyMT modeling framework. This allows the 
    dbSEABED datasets to be easily coupled with other datasets or models that 
    expose a Basic Model Interface.
  doc_url: https://pymt-dbseabed.readthedocs.io/en/latest/
  dev_url: https://github.com/gantian127/pymt_dbseabed

extra:
  recipe-maintainers:
    - gantian127
